updateDocsWhiteList:
  - BUG
  - Chore
  - minor

updateDocsComment: >
  :pray: Thanks for opening this pull request! The maintainers of this repository would appreciate it if you would update some of our documentation :clipboard: based on your changes.

requestInfoReplyComment: >
  We would appreciate it if you could provide us with more info :clipboard: about this issue/pull request!

requestInfoLabelToAdd: request-more-info

newPRWelcomeComment: >
  :pray: Thanks so much for opening your first pull request here!

firstPRMergeComment: >
  :confetti_ball: Congrats on merging your first pull request here! :tada: How awesome!

newIssueWelcomeComment: >
  :pray: Thanks for opening this issue, a maintainer will get back to you shortly!

sentimentBotToxicityThreshold: .7

sentimentBotReplyComment: >
  Please be sure to review the code of conduct and be respectful of other users. cc/ @MathematicsCLtd

lockThreads:
  toxicityThreshold: .7
  numComments: 2
  setTimeInHours: 72
  replyComment: >
    This thread is being locked due to exceeding the toxicity minimums. cc/ @MathematicsCLtd
